services:
  - type: web
    name: uniswap-leaderboard-backend
    env: rust
    buildCommand: cargo build --release
    startCommand: cargo run --release
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RUST_LOG
        value: info 

        